### ISSUE TITLE
Dou Dizhu reward

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#102]
1) The reward in Dou Dizhu isn't described in your documentation, like all the other rewards are
2) The reward is +1 for winning but 0 for losing. Normally, this would be +1 and *-1* for losing, and is like this in all the other environments. This seems like a bug?

@lssr

**Comment by daochenzha** [comment]
Thanks for pointing out. We will make the document clearer. The reason why we consider 1 and 0 are that the average reward can directly reflect the win rates, which are more intuitive for Dou Dizhu. +1 and -1 are intuitive for Texas Hold'em because they refect winning chips. Of course, +1 and -1 will also work.

**Comment by justinkterry** [comment]
"The reason why we consider 1 and 0 are that the average reward can directly reflect the win rates, which are more intuitive for Dou Dizhu." Could you please explain what you mean by that? That makes no sense to me.

**Comment by daochenzha** [comment]
If we play many games and obtain an average reward in evaluation. Then the value of the average reward is just the approximated win rate. It is intuitive for Dou Dizhu since people usually care about the win rate in Dou Dizhu.

**Comment by justinkterry** [comment]
Any updates here?

**Comment by daochenzha** [comment]
@justinkterry The document of Dou Dizhu has been updated. Now it should be clear.

**Comment by justinkterry** [comment]
Link? I don't see it. I also meant did you change the reward to 1,-1 or if not could you please have the environment take different rewards as arguments?

**Comment by daochenzha** [comment]
@justinkterry It is here and will be merged to the master branch soon. https://github.com/datamllab/rlcard/blob/dev/docs/games.md#payoff

We prefer to keep it as 0, 1 because it reflects the winning rates. We are considering putting a config file in each environment to configure some parameters (not only reward but also some parameters of the game). However, it needs some efforts. We may support what you mentioned at that time. But we don't have time to do this in the near future.

If you really prefer 1, -1, you may rewrite payoff function, or use another wrapper for now?
