### ISSUE TITLE
Justification of Gin Rummy Rewards

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#103]
Could you please explain why the Gin Rummy rewards are the way they are? They seem very arbitrary compared to the other rewards.

@lssr

**Comment by daochenzha** [comment]
Hopefully, @billh0420 could give some explanations. Let's discuss whether the design is acceptable.

**Comment by billh0420** [comment]
Yes, the rewards are arbitrary.

With random play by both players, the game ends with knock: 3.65%, with gin: 0.06%, and with dead hand: 96.29%. With modicum of skill, the game should seldom end with dead hand.

Thus, my first goal is to get the trained agent to knock or gin. The agent should be keeping cards that have formed melds and discarding high cards that have little potential to form melds. This is easy to observe if the trained agent is doing this.

In normal scoring for gin rummy, there is a comparison of the deadwood count of both players when the hand ends. I decided, for the first cut in training agents, that I would ignore the opponent. This makes it easier to understand what the trained agent is learning.

In normal scoring for gin rummy, neither player scores any points when the game ends with dead hand. It would be bad to assign a score of zero in this case: you want to penalize the player for not forming melds (which is reflected in his deadwood count). Thus, when the game ends with dead hand, I reward the player with -deadwood_count (divided by 100 to normalize it between -1 and 1).

This reward for a dead hand should get the trained agent to form melds and to go out with knock or gin. The reward of 0.2 for knock and 1.0 for gin is arbitrary. You can vary the 0.2 for knock to persuade the trained agent to gin more or less. You want some amount of gin hands to occur.

I did not want to consider the cases where the opponent could undercut the player that knocks. This changes the strategy: as the game progresses, a player should prefer trying to gin over knock because of the greater chance of being undercut. But, this makes it harder to see if the agent is learning since the optimal strategy is more complex.

Of course, you can change the rewards to be whatever you want. It might be even better to treat knock and gin the same by giving both a reward of 1.0. Then, the trained agent should knock at the first opportunity (which is easy to check if it is being done).

**Comment by justinkterry** [comment]
Why don't you may the 1 and .2 rewards arguments to the environment then, if there's question about what's optimal for them? 

Additionally, you said 

> Thus, when the game ends with dead hand, I reward the player with -deadwood_count (divided by 100 to normalize it between -1 and 1).


1) You mean normalize between 0 and -1 right?
2) The documentation makes no mention of this normalization.

**Comment by billh0420** [comment]
@justinkterry asked "Why don't you make the 1 and .2 rewards arguments to the environment then, if there's question about what's optimal for them?"

I chose to allow the reward payoff to be coded by the user. When you create the two environments:

    env = rlcard.make('gin-rummy')
    eval_env = rlcard.make('gin-rummy')

you can replaced the scorer of the game for the environments with your own scorer. In the final version, one will have to use the scoring done in the standard game of Gin Rummy (which is the difference of the two scores if no undercut or 25 + difference of the two scores if undercut). For a dead hand, you probably want to keep the negative of the deadwood even though it should be zero.

I also have the intention of making the scoring completely different than Gin Rummy to try to see if I can train simpler cases. For example, one could have the score be such that the player loses 1 point for each card over seven. Here the strategy is to try to discard cards over seven and keep cards seven or less. There are other variations a little more complex than this but not as complex as trying to form melds.

@justinkterry said "You mean normalize between 0 and -1 right?"

I was thinking of all the possible scores attainable, including the 0.2 and 1.0 scores.

@justinkterry said "The documentation makes no mention of this normalization."

I need to correct the documentation. It should have had the scores divided by 100.

**Comment by justinkterry** [comment]
Could you please explain what replacing the scorer with my own would look like a little more?

**Comment by justinkterry** [comment]
Also, why .2? .2 just seems super weird to me. Why not .5? At least that's a "round" number.

**Comment by justinkterry** [comment]
Also, are you sure that the deadwood count can ever get as high as 100? Surely the maximum is at least less than 52. Wouldn't dividing by the maximum deadwood score be more natural?

**Comment by billh0420** [comment]
@justinkterry said "Surely the maximum is at least less than 52."

Consider the hand: [KS, KH, QD, QC, JS, JH, TD, TC, 9S, 9H]. Its deadwood count is 98.

**Comment by billh0420** [comment]
@justinkterry asked "Also, why .2? .2 just seems super weird to me. Why not .5?"

If both rewards were 1.0, then the best strategy is to always knock as soon as one can. If the knock reward was 0.0, then I suspect that the best strategy would be to wait till you could gin.

Consider player1 following strategy1 of always knocking and player2 following strategy2 of always ginning. I suspect that there is a reward r for knocking between 0 and 1 that is an equilibrium point for these two strategies. That is, the cumulative rewards for both players over many games will be equal. I don't know what this value of r is.

The training agent will probably encounter the rewards for knocking earlier than the rewards for ginning. One wants to make the reward for ginning more enticing so that the training agent can discover that situation. This is the classic example of small rewards for knocking (easier to do) and big reward for ginning (harder to do before opponent might knock). You would want to see if the agent being trained can detect this situation. But, you need to make the reward for ginning much better than the reward for knocking (I believe).

Consider the case where your opponent never knocks and never gins. This is still an interesting case to see if the training agent can find that ginning is better than knocking (which is will always be if the opponent never goes out).

But, the opponent can go out and can go out quicker if you are always ginning and he is always knocking. There should be some r between 0 and 1 that balances these two strategies.

In the real game of Gin Rummy, the dynamics are quite different. The accepted strategy is to knock early if you can, but to gin rather than knock in the later stages of the game. If you can knock early, you will usually catch your opponent with a huge deadwood count. In the later stages of the game (say half way through), you won't catch your opponent with a big deadwood count and your opponent may even be able to undercut you (especially since he can layoff on your melds). Also, there is a 25 point bonus for ginning and no bonus for knocking.

**Comment by billh0420** [comment]
@justinkterry asked "Could you please explain what replacing the scorer with my own would look like a little more?"

1) Copy gin_rummy_dqn.py from examples into your own working folder.

2) Add and modify stuff at the beginning as follows:

```
from rlcard.games.gin_rummy.player import GinRummyPlayer
from rlcard.games.gin_rummy.utils import utils


def get_payoff(player: GinRummyPlayer, game) -> float:
    payoff = 0.0
    hand = player.hand
    for card in hand:
        rank_id = utils.get_rank_id(card)
        if rank_id <= 9:  # ace to ten are good; face cards are bad
            payoff += 1.0
    return payoff / 10


# Make environment
env = rlcard.make('gin-rummy')
eval_env = rlcard.make('gin-rummy')
for e in [env, eval_env]:
    e.game.judge.scorer.get_payoff = get_payoff
    e.game.settings.is_allowed_knock = False
    e.game.settings.is_allowed_gin = False
    e.game.settings.is_allowed_pick_up_discard = False
    e.game.settings.max_drawn_card_count = 15
env.game.settings.print_settings()
```
3) Run the modified file.

With this payoff, the strategy is to discard face cards if any.

I also changed the settings so that the players are only drawing cards and discarding cards. There is no knocking, ginning, or picking up discarded cards. The game is terminated after 15 cards are drawn (each player gets to discard 8 cards). It would seem that best play will get a score between 0.9 and 1.0. Random play seems to get a score of 0.76.

dqn doesn't seem to do a good job with this. This is a very simple game. I think I could hard-code the weights to perform optimally.

To make the game a little harder, one can change the payoff to consider the rank_id itself: get 10 points for ten or better and the rank value otherwise. Normalize by dividing by 100. The best strategy is to discard the lowest rank card. Now the training agent needs to be able to compare one card with another card (whereas with the first payoff function the training agent needed only to consider the card itself to see if it is good or bad).

**Comment by justinkterry** [comment]
@billh0420 Thanks a ton for your detailed reply. A few follow up questions:

> Also, there is a 25 point bonus for ginning and no bonus for knocking.

What do you mean? This wasn't mentioned in the documentation for this game that I'm aware of

> I suspect that there is a reward r for knocking between 0 and 1 that is an equilibrium point for these two strategies. That is, the cumulative rewards for both players over many games will be equal. I don't know what this value of r is.

This uncertainty seems like a major argument for making this reward an argument to the environment, so that people can easily change it. Is there something wrong with doing that?

**Comment by billh0420** [comment]
@justinkterry asked "What do you mean?  This wasn't mentioned in the documentation for this game that I'm aware of" about a 25 point bonus for ginning.

I am assuming that one knows about Gin Rummy (reading the url about Gin Rummy if needed).

@justinkterry said "This uncertainty seems like a major argument for making this reward an argument to the environment, so that people can easily change it."

My intention was that you would change the get_payoff method as mentioned above.

As an aside, for my goals, I am interested more in understanding the different AI training techniques than in trying to obtain the best agent to play Gin Rummy. By changing the get_payoff method, I can see if the agent can learn the "best" strategy to play with that reward function. As I mentioned above, I am having trouble with dqn learning with the simple reward function of 1 point for holding face card and no points for non-face card. This doesn't seem right and it seems that I am doing something wrong: what is the problem that causes this failure. I want to investigate that.

As another aside, I tried training an agent to play a bridge hand. Rather than trying to solve this difficult problem, I limited myself to where there was only 8 or 12 cards. Then, I limited myself to the case where there was only 8 cards with North holding [AS QS] and West holding [KS 2S] to see if the agent could learn how to finesse. In summary, my aim is to understand what the AI can do more than trying to get the AI to play a "perfect" game with the standard rules of that particular game.

But, if you want to have the AI learn to play with the standard rules, then you can define your get_payoff method to mimic the scoring of the standard rules. But, I think this makes it harder to see what the AI is learning. Of course, you can have a "tournament" of your AI against other ruled based agents to see if your AI is better. However, the stage that I am at now is learning about how to train AI: I have no idea what the best training technique is or what is even available.
