### ISSUE TITLE
Gin Rummy Actions

### ISSUE THREAD

**Issue by lssr** [datamllab/rlcard#106]
What do gin rummy actions 0 and 1 (score_player_0_action and score_player_1_action) do? When would an agent use it?

**Comment by billh0420** [comment]
Each of these actions is the only action that the agent can take. When a player knocks, gins, or declare the hand is dead, the next two actions are player_0 (also called north) calculates his scores and player_1 (also called south) calculates his scores. If I recall, nothing is actually done. I added these two actions at the time because I was unsure how the score (payoff) would get back to the agent being trained if that agent was not the one going out. I later saw that the environment adds the final scores (payoffs) behind the scene to the last action of the agent being trained.

It was also added to provide a hook to put down the melds for each player in the GUI version of the program.
