### ISSUE TITLE
confusing example

### ISSUE THREAD

**Issue by xzhichen** [datamllab/rlcard#11]

**Comment by xzhichen** [comment]
In this example(https://github.com/datamllab/rlcard/blob/master/docs/toy-examples.md#playing-with-random-agents): 
Episode 0
State: {'obs': array([20,  3]), 'legal_actions': [0, 1]}, Action: 0, Reward: 0, Next State: {'obs': array([15,  3]), 'legal_actions': [0, 1]}, Done: False

The player originally has 20 pts, the current card has 3 pts, the player takes action 0, the he should have 23 pts in total and should lose the game, why is the reward value 0 and how does "Next State: {'obs': array([15,  3])" come from

**Comment by daochenzha** [comment]
Here, 20 is the points that the player obtained, and 3 is the points that the dealer obtained. When the player chooses action 0 (hit), the player will be given a new card and then his score came to 15. That is because in Blackjack 'A' can be both 11 or 1. This is the first transition in this episode, thus the reward is 0 since the reward is only given at the end of a episode.
