### ISSUE TITLE
Single Agent With Limit Holdem

### ISSUE THREAD

**Issue by befeltingu** [datamllab/rlcard#114]
I am interested in running limit holdem in single agent mode. My code is the following 

`env = rlcard.make("limit-holdem",config={'single_agent_mode':True})
state = env.reset()
`
It errors on env.reset() with 
> ValueError: too many values to unpack (expected 2)

The reason is that in env.py at line 150 from current master the below call returns a single string a string of the action.

`action, _ = self.model.agents[player_id].eval_step(self._extract_state(state))`

Changing to the following works for me 

`action = self.model.agents[player_id].eval_step(self._extract_state(state))`

Currently self.model.agents[player_id] references the rule based limit holdem player and I am not sure if perhaps the player is not conforming to the expected behaviour here or something like that. 

It seems that in single agent model the environment is still expected to have references to an agent / agents. Is it possible to decouple the two? LIke in OpenAI gym the environment doesnt care where the action comes from. It just takes in an action and as long as its legal it returns the state. Is this the goal with Single agent mode as well?
Thanks!

**Comment by daochenzha** [comment]
@befeltingu Thanks for posting this. This is a bug of the rule agent. 

The second returned value of `eval_step` should be a list of probability.  This design is for our other repo (https://github.com/datamllab/rlcard-showdown) for easier analysis. We will fix it shortly.

Yes. Currently, the single-agent model assumes that the other players use rule/pre-trained models. Thus, our goal here is to train an agent to beat rule/pre-trained model. This setting is simpler than training two agents from scratch at the same time.

I feel like there are some issues if we don't care where the action comes from. Specifically, when we take an action at the current state, our next state is actually from another player. The transition here does not really make sense to me. Thus, I don't expect we are able to train an RL agent with the data. Please let me know if I miss anything.

**Comment by ruzhwei** [comment]
Hello, this bug is now fixed.

**Comment by befeltingu** [comment]
@daochenzha Thanks for the response and thanks to @ruzhwei for the fix. 

I suppose my last comment was not relevant to the bug so should probably be put elsewhere but I suppose I was trying to understand the general architecture of rlcard a bit better. I was originally thinking that the environment was something that just cared about the public state and informed players about updates to that public state so that the players could then maintain their own internal state. In this way the environment does not have to know about the players internal state only the actions they make. So if I had a bot that had not been implemented as a player class in Rlcard it could still observe the state as given to it from the environment and make actions and the environment could still update the public state according to those actions. You could also have two human players easily in this way. In RL card I have to make a player class that the system recognizes. Perhaps what I had in mind is not possible or desirable. I just didnt understand why they had to be coupled in this way. Sorry not trying to take up your time on this as its not a bug or anything I was just trying to understand the architecture.

**Comment by daochenzha** [comment]
@befeltingu If my understanding is correct, you are talking about whether the private state logic should be put internally in the package or in an outer player class. We think it is more efficient to put it within the package since the private state logic is actually the same for each user. It could make things more difficult if we expect the user to implement the logic. Please correct me if I am wrong.

I feel like you are talking about the `run` interface. Yes, this function indeed makes some assumptions about the agent. However, this interfaces are designed for easier use, thus we have to sacrifice some flexibility.

We have more advanced interfaces which are more OpenAI gym like:
`init_game`: Initialize a new game, like env.reset() in gym
`step`: Return the current player ID and the private state
`step_back`: Take one step backward
'get_perfect_information': Return the public state (only works for Leduc and Texas Hold'em for now)

With these interfaces, you don't need to make any assumption on the agent class. Please let me know if you have any suggestions.

**Comment by befeltingu** [comment]
@daochenzha Yes, you put it better than I did. Ya, that certainly makes sense that the state logic will be consistent from one agent to the next and so that becomes something that is assumed to be in place. 

Thanks for pointing out the more advanced interfaces that helps actually. I will take a look and thanks for the response. No suggestions for now but I like the project and will certainly be digging into the code a bit more.
