### ISSUE TITLE
Sparse Mahjong rewards?

### ISSUE THREAD

**Issue by weepingwillowben** [datamllab/rlcard#156]
In my own experiments, I am only getting a non-zero reward from mahjong 1 in 30 games or so. This was calculated by sampling random moves for each player. Is this expected given the nature of the game? If not, is this a problem for other people, or is it just me?

**Comment by lhenry15** [comment]
Yes, it is very hard for random agent to achieve winning situation. Based on our preliminary test, random agent gains 1 non-zero reward (win the game) around every 500 games. Because, random play usually lead to "draw", which means all 13 cards on one's hand is not satisfying the winning condition. You can take a look at [here](http://mahjong.wikidot.com/basic-rules) to learn more about the rule of Mahjong.

**Comment by weepingwillowben** [comment]
Thanks. I was just double checking that this is expected behavior.

**Comment by daochenzha** [comment]
@weepingwillowben I expect some reward engineering could help alleviate the sparse reward problem. Such as giving reward to some good behaviors. RL alone is usually not good at dealing with sparse reward.

**Comment by weepingwillowben** [comment]
Of course. In this case, if I am understanding the problem correctly, it may be sufficient to simply reward longer games by adding a small positive reward at every step.
