### ISSUE TITLE
Feasible on mobile usage?

### ISSUE THREAD

**Issue by pettaa123** [datamllab/rlcard#161]
Nice project,

Recently I did a mobile app for playing [Shithead](https://en.wikipedia.org/wiki/Shithead_%28card_game%29) card game and I would like to add AI to it. I have no ML or RL developing experience and that is how I came to your project. "Shithead" is not that complex, because the action space doesn't consider if the cards are spades, hearts etc. and every card from 2 to ace hase solely one fixed action. Furthermore every player plays on its own. Downside is that there is mostly imperfect knowledge and at least 3 players.

My question is: How long would it take for an implemented AI to calculate its next move? Is it like 1 second or one minute?

**Comment by daochenzha** [comment]
@pettaa123 Hi, I would say it depends on how large the neural network is. The example network in this project is small. But if you use a larger network such as LSTM and more layers of MLP, it could take a longer time to calculate a move. On a personal computer, I think even a large network should take less than 1 second to calculate a move. But I am not sure about the speed on mobile because I do not have experience in mobile development. I think there would be no problem if you deploy the network on the client-side instead of the server-side.

However, the training could be slow if you choose a large network. I would suggest to first develop a rule AI and "initialize" an RL agent with the rules, and then keep training with RL. Another benefit of developing a rule is that you will have a Plan B in case the RL does not work. See my reply in https://github.com/datamllab/rlcard/issues/160

**Comment by pettaa123** [comment]
Hey there,


> I would suggest to first develop a rule AI and "initialize" an RL agent with the rules, and then keep training with RL.

Can I use dqn and a rule based agent? Because in your examples you use random agent with dqn.
