### ISSUE TITLE
Migration to tensorflow 2.x

### ISSUE THREAD

**Issue by FranzPfeifroth** [datamllab/rlcard#216]
Is there an intention ora plan to migrate RLCard to current version of tensorflow?

**Comment by daochenzha** [comment]
@FranzPfeifroth Hi, currently we plan to only support Torch in the next version that will be released soon. Do you think we should support TF as well?

**Comment by FranzPfeifroth** [comment]
I'm trying to implement a german card play called Schafkopf (sheep head).  I am familiar (to some extent) with tensorflow but not with PyTorch. Honestly speaking I think this is not a sufficient reasoning for changing your plans.

**Comment by daochenzha** [comment]
@FranzPfeifroth From our experience, PyTorch has a more user-friendly interface with competitive performance. Nevertheless, after the first release of the new version, we will consider supporting TF 2.X since there are many users out there who will be more comfortable with TF. Thanks for the suggestion :) BTW, we greatly appreciate the contributions of implementing new games if you are interested.

**Comment by FranzPfeifroth** [comment]
Thanks for the quick responses. 
I'll start to implement a Schafkopf environment soon.  Most likely I'll run in multiple problems. It would be great to  get some support in these cases.
