### ISSUE TITLE
doudizhu determine landlord

### ISSUE THREAD

**Issue by sunnyForIOS** [datamllab/rlcard#23]
in function determine_role of doudizhu game，you choose the index 0 as  landlord default, why not add a action named "determine landlord" ,so we can train to decide which player should be the landlord. i just confused

**Comment by daochenzha** [comment]
It is a very good point. Dou Dizhu consists of two phases: (1) bidding; (2) playing. Currently, RLCard only considers the playing phase, to make the setting easier. The playing part is more difficult and could be of greater interest to researchers. Existing papers usually also adopt this setting and evaluate the performance by rotating the roles of the landlord and the peasants. Another choice could be determining the landlord with some heuristic rules.

Of course, it is possible to make "determine landlord" as one of the actions, so that we can train the agents to decide when to bid. It would be interesting to try it by adding a bidding phase a 'bid' action to the game:)
