### ISSUE TITLE
how can i save the cfr model

### ISSUE THREAD

**Issue by DavidLuman** [datamllab/rlcard#26]
save the total game tree?
if do that, how to load it.
and the same problem as deep cfr

**Comment by daochenzha** [comment]
@DavidLuman Thank you for the feedback. It is a good point. Saving CFR should be kind of different. You may save the following dict to files:

https://github.com/datamllab/rlcard/blob/master/rlcard/agents/cfr_agent.py#L18-L23

To load it, just load the files. Then you can do the evaluation or keep training.

For DeepCFR, save the advantage and strategy network. It should be similar to NFSP.

I will update CFR to support save/load model shortly. Thanks :)

**Comment by DavidLuman** [comment]
Thanks for the answer.

Another problem:
I try to train doudizhu model by cfr, but it causes 'maximum recursion depth exceeded'.

Then i find that [the traverse_tree function in cfr_agent](https://github.com/datamllab/rlcard/blob/master/rlcard/agents/cfr_agent.py#L61-L72) traverse all the legal_actions, and doudizhu has large state space, so lead to exceed maximum recursion depth.

I try to reduce legal_actions to reasonable (such as reduce ['3334', '333', '4'] to ['3334'] ), but it dosen't work.

So how to solve the problem. change bfs to dfs? or other better ways.

**Comment by daochenzha** [comment]
Hi, @DavidLuman I have just updated CFR. It should be able to load/save models now.

Indeed, apply CFR on Dou Dizhu needs tremendous computation power since the game tree is too large. Researchers usually design variants of CFR for more efficient traversal or reinforcement learning algorithms for Dou Dizhu.

You can refer to our repo which includes the papers/projects of Dou Dizhu and CFR variants:
https://github.com/datamllab/awesome-game-ai

**Comment by DavidLuman** [comment]
Thank you very much!
