### ISSUE TITLE
What's the difference between InfoSet Number and Avg.InfoSet Size? How could I calculate them? 

### ISSUE THREAD

**Issue by LuoXingyiAFF** [datamllab/rlcard#45]
For example, th InfoSet Number of Dou Dizhu is 10^53 ~10^83, the Avg.InfoSet Size is 10^23, how to explain them and calculate them? Thanks a lot :)

**Comment by daochenzha** [comment]
@LuoXingyiAFF It is a good question. InfoSet Number means the number of possible states from a player's view. For example, in Dou Dizhu, each player can observe his hand as well as all the historical playing sequences. Avg.InfoSet Size means the size of the information set. There are actually many states within an information set since the other players' hands are unseen and have many possibilities. Avg.InfoSet Size is the average number of states over all the information sets.

For Dou Dizhu, the estimation is actually rough. It is challenging to estimate them since there are too many combinations in Dou Dizhu. We do this calculation like this.

InfoSet Number - We calculate it based on an extreme case from the view of player 1. For other cases, the number is orders of magnitude smaller than this extreme case. Suppose player 1 and 2 both have one hand, and player 3 has finished his hand. Given that Dou Dizhu does not care about the suits, the possible permutations for the historical sequences are 54! / ((4!)^13. This accounts for the lower bound of the estimation. However, there are still many possibilities. For example for sequence "3344", it could be "33", "44", "3", "pass", "pass", "3", "44", etc. We consider extream cases, i.e., between every two numbers, we can 1)do not split, 2)split, 3)split and insert a pass, or 4)split and insert two passes. For the 52 cards on the table, we have 4^13 ways to split them. Thus, the upper bound is 54! / ((4!)^13 * 4^13.

For Avg.InfoSet Size, it is also a rough estimation. We calculate based on the view of the landlord. Each peasant player can have 1~17 cards. Thus there are actually 17 * 17 = 289 cases. We average the size of inforSet by (C^{17}_{54} * C^{17}_{37} + ... + C^{1}_{54} * C^{1}_{53}) / 289, where C^{}_{} is the notation for the number of combination.

Note that, the above just shows an estimation to help you get a sense of the difficulty of the game. The correctness is not guaranteed. Let us know if you have better estimations. Thanks :)
