### ISSUE TITLE
how to get the perfect information?

### ISSUE THREAD

**Issue by zhengsx** [datamllab/rlcard#72]
Hi rlcard team, awesome work!

I'd like to know could I get perfect information for the game and how? e.g., can I get all cards information of three players in Doudizhu?

Thanks!

**Comment by daochenzha** [comment]
Hi @zhengsx Thank you for the feedback. We currently do not support an interface to get perfect information since card games are imperfect information games. If you really want to obtain the perfect information, you may need to look into the game engine and fetch whatever you want. 

We are working on a new version in dev branch. Do you think an interface of perfect information would be helpful? We may add this interface to the new version if this interface is very important.

**Comment by zhengsx** [comment]
Thanks for your reply! I'll try to hack the engine and see whether I can get what I need.

I think it's somehow useful if the API would be flexible to provide the perfact information, e.g., there are some research works that investigate how to guide imperfact information by perfact information. It may be helpful for cardgames.

**Comment by daochenzha** [comment]
@zhengsx Thank you for letting us know! We will support this interface in the new version.

**Comment by zhengsx** [comment]
btw, any schedule for new version?

**Comment by daochenzha** [comment]
@zhengsx Hi, most of the new features in the new version are finished. But we do meet some issues before the release (mainly, GUI, leaderboard, and some interfaces). So we need some time for testing. If everything goes well, it should be available in around one month.

**Comment by gogov5** [comment]
> @zhengsx Hi, most of the new features in the new version are finished. But we do meet some issues before the release (mainly, GUI, leaderboard, and some interfaces). So we need some time for testing. If everything goes well, it should be available in around one month.

Hi,  does the perfect information API release?  I want to use this API in rule based Agent to help training.  thanks

**Comment by daochenzha** [comment]
@gogov5 `get_perfect_information` will return a dictionary with perfect information. Currently, it supports Leduc Hold'em and Limit/NoLimit Texas Hold'em. I will let you know when the interfaces for other games are available.
