### ISSUE TITLE
State Encoding of Uno

### ISSUE THREAD

**Issue by lssr** [datamllab/rlcard#83]
I am confused by the state encoding of Uno. According to the documentation, the default state is encoded into 7 feature planes with each plane having a one-hot encoding of all possible cards. Planes 0 to 2 represent the player's hand, as seen in the example below. However, Plane 0 is just the _inverse_ of Plane 1 and Plane 2 is always all zeros. The same pattern is repeated for Planes 4 to 6. Is there any reason for this?

##### State example obtained during an Uno game.
``` 
[[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]]
```

**Comment by daochenzha** [comment]
@lssr Hi, a quick response. Planes 0-2 represent 1 card, 2 cards, 3 cards, respectively. Thus if we add planes 0-2 in element-wise, we obtain an all 1 matrix.

In your example, only the (3,8) of plane 1 is 1, with others 0. (3,8) corresponds to "y-8", which is "yellow 8". This means there is one "yellow 8" card in hand and 0 other cards. If we have two "yellow 8" card in hand, then the (3,8) of plane 2 is 1 instead of plane 1. Plane 2 is a zero matrix here because we do not have a pair of cards for any of the cards.

Thank you for mentioning this. We will modify the doc to make it clearer.

**Comment by lssr** [comment]
Thanks @daochenzha for the quick response. Now, I understand the overall concept. Nevertheless, you mentioned that Plane 0 represent 1 card. Will this mean that, in my example, I have almost all the cards?

Based on your answer, Plane 1 represents 1 card and Plane 2 represents 2 cards but Plane 0 is unclear.

**Comment by daochenzha** [comment]
@lssr Sorry, it is my typo. Planes 0-2 represent 0 card, 1 card, 2 cards, respectively. There are no 3 cards in UNO. I have corrected it in the original comment.

**Comment by lssr** [comment]
Also important to specify in the documentation that Planes 4-6 represent the other player's hand and not the recent three actions.

**Comment by CaoYuanpu** [comment]
@lssr Thanks! The documentation has been modified.
