### ISSUE TITLE
Reverse String Encoding of Cards in State (Gin-Rummy)

### ISSUE THREAD

**Issue by lssr** [datamllab/rlcard#88]
In Gin-Rummy, the string encoding of cards is in reverse order compared to all others games. 

Gin-Rummy: rank + suit
Other Games: suit + rank

**Comment by daochenzha** [comment]
@billh0420 Do you think it would be OK to reverse the rank and suit, or you think rank + suit is a better choice?

**Comment by billh0420** [comment]
I am not sure what Issr means by string encoding of cards. I am just displaying a card in the format "KS" no matter how it is encoded in the program. It appears that I am the only one using the __str__ method to get a printable output of a card.

It is not clear what is meant by encoding a card. I have a class Card that has the instance variables rank: str, suit: str, rank_id: int, suit_id: int, card_id: int. I covered all the standard method of encoding a card by string rank and string suit, or int rank_id and int suit_id, or int card_id. Any three of these combinations can be said to encode the card. I really didn't say which one is "the" encoding. I prefer card_id but I say that was not being used, so I gave all three possibilities and the user can choose whatever he likes.

Or, maybe, Issr is just saying how cards are being displayed. From my brief glance, it appears that cards are being displayed by trying to print out several lines to give a pictorial representation of the card or by printing out the enhanced representation "♠K". I haven't seen any example of "KS" vs "SK".

I have seen (or it doesn't bother me) the forms "♠K", "K♠", and "KS". I haven't seen "SK" and thus it seems strange to me. Also, I prefer "♠K" over "K♠" because that's what I am use to.

**Comment by daochenzha** [comment]
@billh0420 Thanks for the reply. Then I would make the cards in the other games be displayed as rank + suit. I personally do not like "♠K", "K♠", because the special characters of "♠" could cause problems.

**Comment by billh0420** [comment]
I see now what Issr is saying. The other games use the method of get_index() of Card that returns a string (e.g. "SK") and the other games use that in their state representation. In Gin Rummy, the state just uses the object instance of Card itself in its state representation. So, I guess the question is whether the states should be using a string representation of a card or the instance of the Card class itself. And, if the string representation is desired, what order should the suit and rank be given in. Since the state representation is invisible to the user, it probably doesn't matter. Since the state representation is visible to the developer when debugging, it probably matters somewhat.

**Comment by daochenzha** [comment]
@billh0420 We can use card class internally in the game engine. But I vote for the string representation with rank + suit as an external interface. In this way, users do not have to know what classes are used internally in the game engine.

**Comment by daochenzha** [comment]
@billh0420 Let's keep using suit + rank. It is just an order, not a big difference. If we change to rank + suit, many games may have problems. The order is not that important.
